Game logic
SigmaSam/Tic-Tac-Toe-Microverse. pull request #4
Opened 2020-08-15 21:20 UTC by balerum03

- Suggested branch name game_logic.
- Add real logic for your game - get rid of all inline comments and mocked logic used in previous milestone.
- As main.rb file should be responsible for user interaction, this is the only(!) one place where puts/print and get.chomp can be used.
- Think how you can encapsulate diffrent parts of game logic in classes. Do not create one class for everything.
- Read about DRY rule and use it.
- Think about the diffrence between attr_readers/attr_writers and atrr_acessors. Use atrr_acessors only if you really need it.
- Remember about single responsibility rule. Always.
- Remember to cover edge cases: think what player could try to do to cheat the game and make sure that your program does not allow to perform invalid action.

2020-08-15 23:26 UTC, voscarmv requested changes
# Nice work so far, team. 👍 

- The game works properly. Congratulations on the correct game logic!

## However, there are some changes required 👀 🧰 🔨 🔧 

- In order for your `bin/main` file to be properly executable, the first line must be `#!/usr/bin/env ruby`, not `# Variable definition area`. Please fix this.
- It's time to organize your code into classes! Create one class for each part involved in the game logic (e.g. board, players, game, etc...), and then group the methods involved in inside their corresponding class.
- These classes should not be a part of the `bin/main` file. You should create new files inside the `lib` directory for these game logic resources.
- You should access these resources from the `bin/main` file using `require` or `require_relative`.
- Only the `bin/main` file should contain `puts` and `gets chomp` calls. The classes in `lib` should only handle game logic, not input/output functions!
- Make sure that you make proper use of `attr_readers/attr_writers/attr_accessors` in your classes.


### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-08-17 20:59 UTC, kubilaycaglayan requested changes
Hello Team :wave: 
Status: Changes Required :recycle: 

Great job on making the changes! :star: 
And the gameplay is great too:star2: 

Let's cover the details together :arrow_down: 

- [ ] All game-logic related resources (classes and/or modules) are kept in the `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

:bulb: I've added inline comments, _see the comments below please_.

- [ ] DRY rule should be respected.

**DRY means don't repeat yourself and it is a great implementation principle.**
:bulb: I've added inline comments for your winner check method _check comments below please_

Thanks for your efforts and time :+1: 
With all my respect... :pray:

2020-08-17 20:59 UTC, kubilaycaglayan commented on bin/main
>      end
Move logic into the lib folder. There shouldn't be any logic in main.rb.

2020-08-17 20:59 UTC, kubilaycaglayan commented on bin/main
> +  given_number = interface.input_request(itr, players.player1, players.player2, board.board)
I understand why you use 9 here. It feels logical at first sight. But we prefer to use infinite loops with terminating conditions. Please, switch this into an infinite loop and form a proper control mechanism to end that loop.

2020-08-17 20:59 UTC, kubilaycaglayan commented on bin/main
>      end
Let's move the logic into the lib folder. We don't want any logic inside the main.rb.

2020-08-17 20:59 UTC, kubilaycaglayan commented on lib/board.rb
> +      true
Would you consider doing something like this?

```ruby
  def check_win(player_symbol)
    # for rows
    all_equal(board[0..2], player_symbol) ||
    all_equal(board[3..5], player_symbol) ||
    all_equal(board[6..8], player_symbol)

    # and analogical as above for columns and diagonals
  end

  def all_equal(subarray, player_symbol)
    return true if subarray.uniq.size == 1 && subarray.uniq == player_symbol
  end
```

2020-08-17 20:59 UTC, kubilaycaglayan commented on bin/main
> +      puts "The winner is #{players.payer2}"
Move the logic into the lib folder please. 
**And for all the other logic, do the same please.**

2020-08-18 18:55 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

Great job implementing the changes requested by my colleagues :ok_hand: 

However, you have a bug. Kindly check the inline comments for more info.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-18 18:55 UTC, expjazz commented on lib/board.rb
> +    win_arr.each do |arr|
- [ ] This should be @win_arr. I got an error on my console without it.

![image](https://user-images.githubusercontent.com/61479648/90553338-9a50f000-e16a-11ea-90be-4d1be3c91850.png)

2020-08-18 20:22 UTC, krys2fa commented
# Status: Project Approved! 🥇 

Congratulations on making all the requested changes and getting this project approved. 👍 
You can now merge this branch into the master branch and go on with your next project.

💡  Do not forget to submit your project completion form after merging this branch.

#### Nice-To-Haves:
The following are a few **optional** suggestions to make your game better:
- [ ] [OPTIONAL] Your game currently accepts numbers as player names. Checking for names will be great.
- [ ] [OPTIONAL] Your game ends as soon as there is a draw or a win. It will be better to have the game ask the players to play again or to end the game.

All the best team,
Chris

2020-08-18 20:48 UTC, merged